// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  allSidebar: ['intro'],
  javaSidebar: ['java/intro'],
  toolsSidebar: [
    {
      type: 'category',
      label: '开发工具',
      items: ['tools/jetbrains-idea',],
    }
  ],

  algorithmSidebar:[
    'algorithm/intro',
    { type: 'category', label: '前置知识', items: [{ type: 'autogenerated', dirName:'algorithm/pre', }]},
    { type: 'category', label: '基础-排序算法', items: [{ type: 'autogenerated', dirName:'algorithm/basic/sort', }]},
    { type: 'category', label: '基础-搜索算法', items: [{ type: 'autogenerated', dirName:'algorithm/basic/search', }]},
    { type: 'category', label: '数据结构', items: [{ type: 'autogenerated', dirName:'algorithm/ds', }]},
  ],

  momSidebar: [
    { type: 'category', label: '快速开始', items: [{ type: 'autogenerated', dirName:'mom/quick-start', }]},
    { type: 'category', label: '功能使用', items: [{ type: 'autogenerated', dirName:'mom/use', }]},
    { type: 'category', label: '后端部分', items: [{ type: 'autogenerated', dirName:'mom/back-end', }]},
  ],

  devopsSidebar: [
    { type: 'category', label: '项目管理-Jira', items: [{ type: 'autogenerated', dirName:'devops/jira', }]},
    { type: 'category', label: '文档管理-Confluence', items: [{ type: 'autogenerated', dirName:'devops/confluence', }]},
    { type: 'category', label: '制品管理-Nexus', items: [{ type: 'autogenerated', dirName:'devops/nexus', }]},
    { type: 'category', label: '监控预警-Prometheus', items: [{ type: 'autogenerated', dirName:'devops/prometheus', }]},

  ],


  // api: [
  //   'hello', // The navbar item will be linking to this doc
  //   // 'Java导航',
  //   // {
  //   //   type: 'autogenerated',
  //   //   dirName: 'java',
  //   // },
  // ],

  // javaSidebar: ['java'],

  // algorithmSidebar: ['algorithm'],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
